### PR TITLE
Primary nav restyle

### PR DESCRIPTION
**Pull request by edwardcasbon**
Following style/design updates from @petewoodhouse-rg at https://www.figma.com/file/493eg357bvwUIRB0KD5G27/Website-page-templates?node-id=141%3A859.

**Note: Before merging**, we'll need to update the package version number. It shouldn't be a breaking change, but worth updating it as a point release, e.g. `v10.16.0` rather than `v10.15.28`.

### CODE REVIEW

**Comment by philscott-rg** [comment]
I get this overlap happening between widths of 1480px down to 1200px: 

image

**Comment by edwardcasbon** [comment]
> I get this overlap happening between widths of 1480px down to 1200px:
> 
> image

Thanks @philscott-rg , but I think that's more of an issue for the Redgate website, than the header in the web toolkit?

**Comment by philscott-rg** [comment]
Yes, true! I'll put it in there

**Comment by edwardcasbon** [comment]
Merged in (by hand) by https://github.com/red-gate/honeycomb-web-toolkit/commit/57c10a6dacaa21c9dcd8196420bc4c1c0a47338a .

**Pull request closed without merging**
