### PR TITLE
Update jQuery to the latest version (v3.4.1)

### PR DESCRIPTION
**Pull request by edwardcasbon**
Linked to https://github.com/red-gate/honeycomb-web-toolkit/issues/137

### CODE REVIEW

**Comment by philscott-rg** [comment]
I've had a click around the honeycomb docs with jquery-migrate, and there are a few deprecation warnings that I might try and get rid of:

```
/docs/js-library/viewport.htm
JQMIGRATE: jQuery.fn.scroll() event shorthand is deprecated
JQMIGRATE: jQuery.fn.resize() event shorthand is deprecated


/docs/js-library/carousel.htm
JQMIGRATE: 'ready' event is deprecated
JQMIGRATE: jQuery.fn.focus() event shorthand is deprecated


/docs/js-library/lightbox.htm
JQMIGRATE: jQuery.fn.unbind() is deprecated
JQMIGRATE: jQuery.fn.bind() is deprecated
JQMIGRATE: jQuery.fn.blur() event shorthand is deprecated
JQMIGRATE: jQuery.fn.click() event shorthand is deprecated
```

It looks like these come from 3rd-party code - the carousel and lightbox warnings are from slick and fancybox, which have newer versions available, so I'll try upgrading. 

The viewport warning is from this mystery script: https://github.com/red-gate/honeycomb-web-toolkit/blob/f8ceb146c66503fad0225c384c80373299f6f73e/dist/document/vendor/jquery.inViewport.min.js#L1
@edwardcasbon do you have any memory of where that came from?

**Comment by edwardcasbon** [comment]
> @edwardcasbon do you have any memory of where that came from?

Yeah, I think that's one of mine, from years ago! - https://github.com/edwardcasbon/jquery.inViewport/blob/master/jquery.inViewport.js

**Comment by philscott-rg** [comment]
Oh cool! That's very handy - it might just need reminifying with a modern minifier, in that case? It looks like the original minification must have added the deprecated syntax.

**Comment by philscott-rg** [comment]
> it might just need reminifying 

It actually does need a little update in the source, so I've done that as a PR for the original

**Comment by philscott-rg** [comment]
I've updated inViewport and slick, which has removed the deprecation warnings for those components.

I've also updated fancybox to its latest version, but the deprecation warnings are still there! I don't think there's much do to about that without replacing fancybox completely, which doesn't seem worth the trouble yet. 

So I think this PR might be ready to go?

**Pull request merged**
